package ChatTo;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;

import com.sun.tracing.dtrace.ArgsAttributes;

/**
 *
 * @author  __USER__
 */
@SuppressWarnings("serial")
public class ClientFrame extends javax.swing.JFrame {
	ChatClient chatClient;

	/** Creates new form ClientFrame */
	public ClientFrame(String username) {
		chatClient = new ChatClient();
		un = username;
		java_thread();
		chatClient.connect(un);

		initComponents();
		/*System.err.println(port+" "+iAddress+" "+user);*/
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		textField1 = new java.awt.TextField();
		textArea1 = new java.awt.TextArea();
		button1 = new java.awt.Button();
		button2 = new java.awt.Button();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		button1.setLabel("\u53d1\u9001");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});

		button2.setLabel("\u53d1\u9001\u6587\u4ef6");
		button2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button2ActionPerformed(evt);
			}
		});

		jMenu1.setText("\u5f53\u524d\u5728\u7ebf\u7528\u6237");
		jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jMenu1MousePressed(evt);
			}
		});

		jMenuItem2.setText("Item");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2Performed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("Item");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3Performed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuItem1.setText("Item");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1Performed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem4.setText("Item");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4Performed(evt);
			}
		});
		jMenu1.add(jMenuItem4);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						textField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						371,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						textArea1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						380,
																						Short.MAX_VALUE))
																.addContainerGap())
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		button2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(44, 44,
																		44)
																.addComponent(
																		button1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(39, 39,
																		39)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(textArea1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										167,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(textField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										76,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														button1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														button2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		button1.setLabel(un);
		pack();
		
	}// </editor-fold>
	//GEN-END:initComponents

	private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
		FileChooser fileChooser=new FileChooser();
		byte array[]=null;
		array=fileChooser.getFile();
		chatClient.sendFile(array, idAddress, iport);
		
		/*ByteArrayInputStream ba=new ByteArrayInputStream(array);
		int a=array.length;
		byte b[]=null;
		b=new byte[a];
		try {
			while (ba.read(b)!=-1) {
				chatClient.sendFile(b, idAddress, iport);
			}
		} catch (IOException e) {
			e.printStackTrace();
		}*/
	}

	private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {
		chatClient.connect("displaylist");
		try {
			Thread.sleep(500);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		list = chatClient.getList();
		int i = list.size();
		System.err.println(i);
		if (i > 0) {
			User user = list.get(0);
			jMenuItem2.setText(user.getUsername());
			i--;
		}
		if (i > 0) {
			User user = list.get(1);
			jMenuItem3.setText(user.getUsername());
			i--;
		}
		if (i > 0) {
			User user = list.get(2);
			jMenuItem1.setText(user.getUsername());
			i--;
		}
		if (i > 0) {
			User user = list.get(3);
			jMenuItem4.setText(user.getUsername());
			i--;
		}
	}

	private void jMenuItem3Performed(java.awt.event.ActionEvent evt) {
		User user = list.get(1);
		idAddress = user.getAddress();
		iport = user.getPort();
	}

	private void jMenuItem4Performed(java.awt.event.ActionEvent evt) {
		User user = list.get(3);
		idAddress = user.getAddress();
		iport = user.getPort();
	}

	private void jMenuItem2Performed(java.awt.event.ActionEvent evt) {
		User user = list.get(0);
		idAddress = user.getAddress();
		System.out.println(123);
		iport = user.getPort();
	}

	private void jMenuItem1Performed(java.awt.event.ActionEvent evt) {
		User user = list.get(2);
		idAddress = user.getAddress();
		iport = user.getPort();
	}

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {
		String string = textField1.getText();
		chatClient.send(string, idAddress, iport);
		textArea1.append("\n" + un + ":" + string);
		textField1.setText("");
	}

	void java_thread() {

		Thread t = new Thread(new Runnable() {
			public void run() {
				while (true) {
					String s = null;
					try {
						s = chatClient.receiveData();
					} catch (ClassNotFoundException e) {
						e.printStackTrace();
					} catch (IOException e) {
						e.printStackTrace();
					}
					if (!s.equals("")) {
						textArea1.append(s);
						idAddress = chatClient.getAhosAddress();
						iport = chatClient.getIport();
					}
				}
			}
		});
		t.start();
	}
    
	/**
	 * @param args the command line arguments
	 */
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button button1;
	private java.awt.Button button2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private java.awt.TextArea textArea1;
	private java.awt.TextField textField1;
	private String un;
	private int iport=0;
	private InetAddress idAddress = null;
	private ArrayList<User> list=null;
	// End of variables declaration//GEN-END:variables

}