import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.swing.JTable;

/*
 * SearchFile.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 * 
 * @author __USER__
 */
public class SearchFile extends javax.swing.JFrame {

	/** Creates new form SearchFile */
	public SearchFile() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		textField1 = new java.awt.TextField();
		jComboBox1 = new javax.swing.JComboBox();
		button1 = new java.awt.Button();
		scrollPane1 = new java.awt.ScrollPane();
		label1 = new java.awt.Label();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"绝对路径名", "文件夹路径名", "文件名", "后缀名" }));

		button1.setLabel("search");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});

		label1.setText("results:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														label1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														scrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														395, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		textField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		218,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jComboBox1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		button1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(23, 23, 23)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														button1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														textField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(2, 2, 2)
								.addComponent(label1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(2, 2, 2)
								.addComponent(scrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										199,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(26, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {

		int i = 0;
		String a = null;
		String b = textField1.getText();
		a = (String) jComboBox1.getSelectedItem();
		if (a.equals("绝对路径名")) {
			i = 1;
		} else if (a.equals("文件夹路径名")) {
			i = 2;
		} else if (a.equals("文件名")) {
			i = 3;
		} else {
			i = 4;
		}

		Object[][] results = getselect(DoMysql.selectserch(b, i));
		String[] title = { "文件" };
		final JTable table_1 = new JTable(results, title);
		
		table_1.addMouseListener(new MouseAdapter() 
		{ 
			public void mouseClicked(MouseEvent e)
		{        
			if (e.getButton()==MouseEvent.BUTTON1) {
				int a=table_1.getSelectedRow();
				 int b=0;
				 
				 String path=new String((String) table_1.getValueAt(a,b));
				 String paString="cmd  /c  start  "+ "\"\" \""+path;
				 try {
					Runtime.getRuntime().exec(paString);
				} catch (IOException e1) {
					e1.printStackTrace();
				}
			}else if (e.getButton()==MouseEvent.BUTTON3) {
				
				int a=table_1.getSelectedRow();
				 int b=0;
				 String path=new String((String) table_1.getValueAt(a,b));
				 File file=new File(path);
				 FileSave fileSave=new FileSave();
				 fileSave.writeData(file);
			}
			
		
				 
		}        
			
		});
		scrollPane1.add(table_1);
	}
	public void openFile(String string) {
		try {
			Runtime.getRuntime().exec(string);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private Object[][] getselect(List list) {
		Object[][] s = new Object[list.size()][1];
		for (int i = 0; i < list.size(); i++) {
			MyFile file = (MyFile) list.get(i);
			s[i][0] = file.getAbsolutePathName();
		}
		return s;

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SearchFile().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button button1;
	private javax.swing.JComboBox jComboBox1;
	private java.awt.Label label1;
	private java.awt.ScrollPane scrollPane1;
	private java.awt.TextField textField1;
	// End of variables declaration//GEN-END:variables

}